NWEB.Practice.T04.Web/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NWEB.Practice.T04.Core;
using NWEB.Practice.T04.Core.Data;
using NWEB.Practice.T04.DataAccessLayer.Infrastructures;

namespace NWEB.Practice.T04.Web.Controllers
{
    public class RequestsController : Controller
    {
        private readonly IUnitOfWork  _unitOfWork;

        public RequestsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Authorize(Roles = $"{SD.ROLE_USER},{SD.ROLE_ADMIN}")]
        public async Task<IActionResult> Index()
        {
              return _unitOfWork.DbContext.Requests != null ? 
                          View(await _unitOfWork.DbContext.Requests.ToListAsync()) :
                          Problem("Entity set 'ClassDbContext.Requests'  is null.");
        }

        [Authorize(Roles = $"{SD.ROLE_USER},{SD.ROLE_ADMIN}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _unitOfWork.DbContext.Requests == null)
            {
                return NotFound();
            }

            var request = await _unitOfWork.DbContext.Requests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        [Authorize(Roles = $"{SD.ROLE_USER}")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,StudentName,ClassName,Title,LeaveDate,LeaveType,Reason,Status")] Request request)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.DbContext.Add(request);
                await _unitOfWork.DbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        [Authorize(Roles = $"{SD.ROLE_USER}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _unitOfWork.DbContext.Requests == null)
            {
                return NotFound();
            }

            var request = await _unitOfWork.DbContext.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,StudentName,ClassName,Title,LeaveDate,LeaveType,Reason,Status")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _unitOfWork.DbContext.Update(request);
                    await _unitOfWork.DbContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }
        [Authorize(Roles = $"{SD.ROLE_USER}")]
        public async Task<IActionResult> Cancel(int? id)
        {
            if (id == null || _unitOfWork.DbContext.Requests == null)
            {
                return NotFound();
            }

            var request = await _unitOfWork.DbContext.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cancel(int id, [Bind("Id,StudentName,ClassName,Title,LeaveDate,LeaveType,Reason,Status")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }
                    _unitOfWork.DbContext.Update(request);
                    await _unitOfWork.DbContext.SaveChangesAsync();
                
                
                return RedirectToAction(nameof(Index));
 
        }
        [Authorize(Roles = $"{SD.ROLE_ADMIN}")]
        public async Task<IActionResult> Approve(int? id)
        {
            if (id == null || _unitOfWork.DbContext.Requests == null)
            {
                return NotFound();
            }

            var request = await _unitOfWork.DbContext.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Approve(int id, [Bind("Id,StudentName,ClassName,Title,LeaveDate,LeaveType,Reason,Status")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }



            _unitOfWork.DbContext.Update(request);
            await _unitOfWork.DbContext.SaveChangesAsync();


            return RedirectToAction(nameof(Index));

        }
        [Authorize(Roles = $"{SD.ROLE_ADMIN}")]
        public async Task<IActionResult> Reject(int? id)
        {
            if (id == null || _unitOfWork.DbContext.Requests == null)
            {
                return NotFound();
            }

            var request = await _unitOfWork.DbContext.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Reject(int id, [Bind("Id,StudentName,ClassName,Title,LeaveDate,LeaveType,Reason,Status")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }
            _unitOfWork.DbContext.Update(request);
            await _unitOfWork.DbContext.SaveChangesAsync();


            return RedirectToAction(nameof(Index));

        }
        [Authorize(Roles = $"{SD.ROLE_USER},{SD.ROLE_ADMIN}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _unitOfWork.DbContext.Requests == null)
            {
                return NotFound();
            }

            var request = await _unitOfWork.DbContext.Requests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_unitOfWork.DbContext.Requests == null)
            {
                return Problem("Entity set 'ClassDbContext.Requests'  is null.");
            }
            var request = await _unitOfWork.DbContext.Requests.FindAsync(id);
            if (request != null)
            {
                _unitOfWork.DbContext.Requests.Remove(request);
            }
            
            await _unitOfWork.DbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestExists(int id)
        {
          return (_unitOfWork.DbContext.Requests?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

NWEB.Practice.T04.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NWEB.Practice.T04.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NWEB.Practice.T04.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NWEB.Practice.T04.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Create">Create Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Index">View Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Index">Manage Request</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - NWEB.Practice.T04.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>